services:
  web:
    build: .
    ports:
      - "8000:8000"
  postgreql:
    image: "postgres:16.4-bullseye"
    restart: unless-stopped
    volumes:
      - ./storage/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=recueil
    ports:
      - 5432:5432