services:
  web:
    container_name: recueil_container
    build: .
    environment:
      - USERNAME=${DBUSER}
      - PASSWORD=${DBPASS}
    ports:
      - "8000:8000"
  postgreql:
    image: "postgres:16.4-bullseye"
    restart: always
    volumes:
      - ./storage/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASS}
      - POSTGRES_DB=recueil
    ports:
      - 5432:5432