services:
  web:
    container_name: recueil_container
    volumes:
      - logs:/app/logs/
    build: .
    environment:
      - DB_URL=postgres://${DBUSER}:${DBPASS}@database:5432/${DBNAME}
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy

  database:
    image: "postgres:16.4-bullseye"
    restart: unless-stopped
    volumes:
      - ./storage/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DBUSER} -d ${DBNAME}"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASS}
      - POSTGRES_DB=${DBNAME}
    ports:
      - 0.0.0.0:5432:5432
    hostname: database  

volumes:
  logs: